#%RAML 1.0 DataType
type: object
properties:
  customerid: 
    type: number
    example: 124
  customername: 
    type: string
    example: rose
  phonenumber: 
    type: number
    example: 99999009
  job:
    type: string
    example: HR
  jobtype: 
    type: string
    enum: [salaried,self-employed,contractor]
    example: salaried
  address: 
    type: string
    example: "mumbai,india" 
  city: 
    type: string
    example: mumbai
  state: 
    type: string
    example: mumbai
  salary: 
    type: number
    example: 50000
      
      

      

      

  

